version: 1
services:
  - type: web
    name: casesnap-ai
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt', download_dir='/opt/render/nltk_data')"
    startCommand: python app.py
    envVars:
      - key: CLOUD_NAME
        value: dlv8etgkl
      - key: CLOUD_API_KEY
        value: 958695759171152
      - key: CLOUD_API_SECRET
        value: Z1ySvHVQkJvl_RXGB6qD45qejlY
      - key: MONGO_URI
        value: mongodb+srv://abhinayanair:2rSQQNNGj37OwVML@cluster0.t5tw7sl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: NLTK_DATA
        value: /opt/render/nltk_data
    region: oregon
